version: '3'
services:
  backend:
    build: ./src
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=/data/database.db
  frontend:
    build: ./app
    ports:
      - "8051:8051"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend